'use strict';Object.defineProperty(exports,"__esModule",{value:true});exports.default = Useless;var _css=require('css');var _css2=_interopRequireDefault(_css);var _cheerio=require('cheerio');var _cheerio2=_interopRequireDefault(_cheerio);function _interopRequireDefault(obj){return obj && obj.__esModule?obj:{default:obj};} /**
 * Useless(html, css) -> css
 */function Useless(html,css){var $=_cheerio2.default.load(html);return reduceCss(css);function reduceCss(css){var ast=_css2.default.parse(css || '');var candidateRules=ast.stylesheet.rules;var activeRules=candidateRules.filter(filterCssRule);ast.stylesheet.rules = activeRules;return _css2.default.stringify(ast);}function filterCssRule(rule){switch(rule.type){case "rule":var result=false;rule.selectors.forEach(function(selector){selector = selector.replace(/(\(|\)|=|\"|@|:|\.|\[|\]|,)/g,'\\$1'); //" <-- atom, :(
var selection=$(selector);if(selection.length > 0){result = true;}});return result;break; /* TODO: these cases could be useful to consider, but I'll handle them later */case "comment":break;case "media":break;case "keyframes":break;case "font-face":break;default:console.debug("Add a case for this!",rule.type);}} /**
   * Note: Leaving this here for now, but design of the tool has changed and probably won't do things this way any more
   * return [{uri, local}, ...]
   */function parseCssToLoad(html,only,ignore){var links=$('link[href$=".css"]'),result=[];Object.keys(links).forEach(function(key){if(!Number.isNaN(Number.parseInt(key))){var el=links[key],obj={};obj.uri = el.attribs.href,obj.local = obj.uri.charAt(0) === '.';result.push(obj);}});return result;} /**
   * Note: Leaving this here for now, but design of the tool has changed and probably won't do things this way any more
   */function loadLocalCss(path){var workdir=options.workdir?pathLib.resolve(options.workdir):'';path = pathLib.join(workdir,path);return fs.readFileSync(path).toString();} /**
   * Note: Leaving this here for now, but design of the tool has changed and probably won't do things this way any more
   */function loadRemoteCss(href){var baseurl=options.baseurl || '';return request('GET',baseurl + href).body.toString();}}
//# sourceMappingURL=useless.js.map